### ISSUE TITLE
Ensure compatibility with at least PHP 7.1

### ISSUE THREAD

**Issue by Chekote** [Medology/FlexibleMink#190]
PHP 5.6 EOL reached end-of-life on Jan 2019. We need to ensure the project supports at least PHP 7.1 so that consumers of this package can run it on a supported PHP version.

Since there are projects utilizing this package that cannot yet update to PHP 7.1, we want to ensure that this project also remains compatible with PHP 5.6 for now. So this issue is to make this package COMPATIBLE with 7.1, NOT REQUIRE 7.1. The project MUST REMAIN COMPATIBLE WITH PHP 5.6.

## Acceptance Criteria
* Project's primary PHP image is using at least PHP 7.1
* All composer dependencies are updated to support at least PHP 7.1
* CI is configured to run tests using BOTH 5.6 and >=7.1 images
* All tests pass on BOTH 5.6 and >=7.1 images

## Notes:
* PHP 7.2 should be stable enough to use. But PHP 7.3, while being released as stable, has caused us some issues on other projects.
* No need to update web image, as this project doesn't use any server-side PHP, only CLI.

**Comment by aserv92** [comment]
The PRs for this story are:
https://github.com/Medology/FlexibleMink/pull/236
https://github.com/Medology/FlexibleMink/pull/237

**Comment by aserv92** [comment]
##QA Information
This is a PHP version change along with docker and CircleCI configuration changes.
This is a PHP library. It is not automatically pulled in to any project and not automatically deployed anywhere.
This cannot be tested by QA.

**Comment by MeganPartida** [comment]
nothing for me to test

updating ticket status from pre-production qa to **deploy & test**

**Comment by MeganPartida** [comment]
Nothing for me to test

updating ticket status from Production QA to **Approval**
