### ISSUE TITLE
Upgrade PHPUnit to v5.7

### ISSUE THREAD

**Issue by hopeseekr** [Medology/FlexibleMink#238]
PHPUnit 4.8 was EOL'd in February 2017 (2 years ago). 

The most up to date version of PHPUnit which still supports PHP 5.6 is 5.7.27.

See https://phpunit.de/supported-versions.html

**Comment by MeganPartida** [comment]
Nothing to test at this time on this issue. will test as more PRs come through for testing.

updating ticket status from pre-production qa to **deploy & test**

**Comment by Chekote** [comment]
Skipping Prod QA since there is no prod for this composer package.
