### ISSUE TITLE
Behat Parallelization Not Working Properly

### ISSUE THREAD

**Issue by juanmrad** [Medology/FlexibleMink#250]
When doing stress test we are running tests several times in order to stress test it. We had to disable this functionality after improving our stress test because parallelization was not properly working and was leaving nodes without test to run and causing a fail. 

We need to make sure that when parallelization happens that all nodes have at least 1 test to run to avoid issues.

**Comment by MeganPartida** [comment]
## QA - Local
nothing for me to verify w/ behat
updating to **deploy & test**

**Comment by MeganPartida** [comment]
## QA - Local
nothing for me to test since it's stress test related
updating to **deploy & test**

**Comment by MeganPartida** [comment]
## QA - Prod
- nothing for me to test
- updating to **approval**
