### ISSUE TITLE
Add support for testing JavaScript JSON objects key-by-key

### ISSUE THREAD

**Issue by hopeseekr** [Medology/FlexibleMink#27]
**Problem:** Testing for exact JSON objects is fraught with many grave difficulties, such as orderIds, dates and other dynamic data constantly changing.

**Need:** The ability to compare two JSON objects, one from JavaScript, one from the Behat tests, on a key-by-key basis, including the keys one wants to test, and ignoring the rest.

**Comment by RedEnchilada** [comment]
Resolved by #28
