### ISSUE TITLE
Import common classes from stdcheck to Flexible Mink.

### ISSUE THREAD

**Issue by christopherhealthlabs** [Medology/FlexibleMink#275]
Description:
In order to avoid duplication of code and keep consistency in how we test our projects, we need to move all common case Behat steps from stdcheck to Flexible Mink (both 1.0 and 2.0). 

Example of Behat case:
```php
public function assertElementAttributeValue(NodeElement $element, $attribute, $value)
    {
        $actualValue = $this->assertElementHasAttribute($element, $attribute);
        if ($value != $actualValue) {
            throw new ExpectationException(
                $attribute . ' attribute has value of: ' . $actualValue . ' expected: ' . $value,
                $this->getSession()
            );
        }
    }
```

Acceptance Criteria:
- [ ] Code is removed from the stdcheck repo and moved to Flexible Mink branches
- [ ] stdcheck is updated to use the latest version of Flexible Mink
- [ ] Issues are created to update the other projects to the latest version of Flexible Mink

**Comment by fortoulrodolfo** [comment]
Bye FlexibleMink
