### ISSUE TITLE
Add additional formatters

### ISSUE THREAD

**Issue by izazueta** [Medology/FlexibleMink#293]
## Requirement
In order to use attributes with specific formats like phone numbers *"###-###-####"* on Behat tests there should be additional formatters on Flexible Mink, right now only support Dates.

When asserting on steps like *I should see "Fax: 281-888-8888"*, if this attribute is stored as a number on the database *2818888888* this won't match unless we hardcode the number on the factory and in the test. This happens on STDcheck LabFactory and some scenarios in editPatient.feature that assert against the fax number.

We need a step along the lines of:

```gherkin
Then I should see (the fax number of the lab in the format (###)-###-####)
```

Much like we have for dates:

```gherkin
Then I should see (the created at of the order in the format MM-DD-YYYY)
```

Make sure this is implemented for Flexible Mink v1 & v2.

**Comment by fortoulrodolfo** [comment]
Good bye FlexibleMink
