### ISSUE TITLE
Stale data returned from getTableFromName

### ISSUE THREAD

**Issue by Chekote** [Medology/FlexibleMink#349]
## Problem:
In FlexibleMink 1.0, the getTableFromName() method would return a cached version of the table structure if it was available and the forceFresh parameter was not true. This worked fine for 1.0, but since 2.0 is intended to be used with the automatic spinning of the BehatRetryExtension, it was preventing the retry from ever passing. This was due to the first call returning the fresh table data that did not pass the assertion, and subsequent calls would receive the stale data even if the real table on the page had updated and should pass the assertion.

**Comment by HLCharlie** [comment]
Waiting on feedback from QA and will address as necessary.

**Comment by Chekote** [comment]
Scored with @johnnie502 and @rashidsaf

**Comment by splinfer** [comment]
## QA Prod

Moving forward with this ticket. Nothing to test here.
