### ISSUE TITLE
Update chekote/noun-store

### ISSUE THREAD

**Issue by manuerumx** [Medology/FlexibleMink#367]
# Story

## Description
As a result of an attempt to [update Laravel in Stdcheck](https://github.com/Medology/stdcheck.com/issues/8679), it was discovered that several dependencies need to be updated first.
For this project is was detected is using a `chekote/noun-store` dependency that although it is not used by Laravel, it requires another dependency, which when Laravel is updated, it will also be updated and the version defined in this project prevents its use, making impossible to update STDCheck due to incompatibilities in that dependency.

## Negative Impact:
Devs cannot update other projects which use this as a dependency.

## Business Value
Reduces the time invested in maintaining the project updated.

## Notes
- The issue is part of the epic to [Update stdcheck to Laravel 6](https://github.com/Medology/stdcheck.com/issues/12864)
- `chekote/noun-store` dependency must be updated in this project, before STDcheck can be updated

## Acceptance Criteria
- [ ] Update the project to include the latest version available for the `chekote/noun-store` dependency

## Announcement Message
releasenotes: N/A

devchat: FlexibleMink is now compatible with Laravel 6.

# Proposed Solution:
Update `chekote/noun-store`  to the latest version.
Ensure tests still pass.

## How will the proposed solution address the negative impact(s)?
The changes make this package compatible with Laravel 6.

## Side Effects
Is possible some methods may require changes.

## QA Needs
Since this is a library, it is not possible to manually test this from an end-user perspective. So we will wait until the PR for STDcheck which pulls in this new version before we perform manual testing.

## Subject Matter Experts
- Donald (General & noun-store)
- Johnnie (General)
- Juan (General)

**Comment by Chekote** [comment]
I am going to close this issue because although the package's lock file is at 4.0.0 for noun-store, its composer.json file is compatible with 4.0.1. Since a package's lock file plays no role in resolving the dependency graph for the host project, it is not actually necessary to make any changes to FlexibleMink when wanting to use noun-store 4.0.1 in STDcheck.
