### ISSUE TITLE
Enable artifacts and insights in CircleCI

### ISSUE THREAD

**Issue by PayneWheat** [Medology/FlexibleMink#406]
# Story

## Short Summary
To aid with debugging IFT/CFTs, we should store test artifacts and CircleCI's insights for this project.

## Acceptance Criteria
- [ ] Configure CI to store artifacts
- [ ] Configure CI config to support test insights

## Subject Matter Experts
Johnnie
Rodolfo

## Notes
[Documentation on artifacts](https://circleci.com/docs/2.0/artifacts/?source=post_page---------------------------&utm_source=google&utm_medium=sem&utm_campaign=sem-google-dg--uscan-en-dsa-maxConv-auth-brand&utm_term=g_b-_c__dsa_&utm_content=&gclid=Cj0KCQjw8eOLBhC1ARIsAOzx5cHMQfW9EoTxQmsKmeYZhdjB7jRLo1dn0p47Cwl8EMwuKhUFVJl8FZAaAjYtEALw_wcB)
[Documentation on setting up insights](https://circleci.com/docs/2.0/collect-test-data/)

This project uses Behat tests, so view the configuration for STDcheck or HealthLabs for insight.

## Announcement Message
Artifacts and test insights have been enabled for FlexibleMink

**Comment by fortoulrodolfo** [comment]
Team Umami will take care of this implementation
