### ISSUE TITLE
Use getBoundingClientRect

### ISSUE THREAD

**Issue by joshmedeski** [Medology/FlexibleMink#78]
Refactor container context with JS to remove custom data- attribute and use getBoundingClientRect instead

https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect

**Comment by RedEnchilada** [comment]
@joshmedeski Where are we removing this from?

**Comment by Chekote** [comment]
Closing this as the visibility and z-indexing functionality really needs to be implemented as a full composer package.
